# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/n2a-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter n2awifi,$(TARGET_DEVICE)),)

endif
